server:
  port: 8888
  servlet:
    context-path: /z11g

# connect database
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: dangan
    password: 123456

  # redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: #默认为空
    jedis:
      pool:
        max-active: 20
        max-wait: 5
        max-idle: 10
        min-idle: 0
    timeout: PT30M #30分钟
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.z11g.base.model

# mybatis plus SQL logging
logging:
  level:
    cn.z11g.demo.mapper: debug